### ISSUE TITLE
I can't see sql file and too much files

### ISSUE THREAD

**Issue by raklibhasanacc** [ashraf-kabir/personal-blog#1]
Please add database sql file and please remove unwanted files. I see that your script have lots of files and your file size is: 38mb after extract.
Your code running/outputting so faster, so i want to use your codes. Please add sql file and improve your code and make more very faster loading. Sorry for not good english. thanks

**Comment by CodeLife01** [comment]
please share the sql file...

**Comment by halojoy** [comment]
Same for me.
I miss .sql for creating tables.
Please add this.

**Comment by ashraf-kabir** [comment]
@raklibhasanacc @CodeLife01 @halojoy 
for sql file email me at ashrafkabir95@gmail.com & mention this repository
