### ISSUE TITLE
sql file for database?

### ISSUE THREAD

**Issue by ferahfeza** [ashraf-kabir/personal-blog#2]
Where can I find the sql file for database? Thank you.

**Comment by alfast456** [comment]
can you upload the SQL file?

**Comment by ferahfeza** [comment]
Sorry, which file is the *.sql file? I could not find or see it.

**Comment by chaithrarajan** [comment]
here is the sql file

**Comment by ferahfeza** [comment]
@chaithrarajan good, but sql file isn't there. Please don't joke me.

**Comment by chaithrarajan** [comment]
Sry even I don't have since there was no database in GitHub I have send u
that. If I get I will send you.

**Comment by ferahfeza** [comment]
Is this script paid or free?

**Comment by ashraf-kabir** [comment]
check the readme
