### ISSUE TITLE
Uncaught PDOException: SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens 

### ISSUE THREAD

**Issue by shahbaazkyz** [ashraf-kabir/personal-blog#7]
Fatal error: Uncaught PDOException: SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens in C:\xampp\htdocs\personalblog\admin\manage-posts.php:124 Stack trace: #0 C:\xampp\htdocs\personalblog\admin\manage-posts.php(124): PDOStatement->execute() #1 {main} thrown in C:\xampp\htdocs\personalblog\admin\manage-posts.php on line 124

**Comment by ashraf-kabir** [comment]
edit when necessary it's an open source of mine
